### ISSUE TITLE
Request: Config for restart timer

### ISSUE THREAD

**Issue by Orcinuss** [ModdedMinecraft/MMCReboot-Sponge#1]
Could you add a config option that allows you to change how long after a vote has completed for the server to restart. Usually when my players vote for a restart the server's TPS is really down and waiting 5 minutes is a bit long. Obviously only when the result of the vote is yes.

**Comment by leelawd** [comment]
Closed by ea2fc04d298f20b7f183cdd2af6dbc1846d6207d

Thank you for the suggestion. It is in v1.3 https://github.com/ModdedMinecraft/MMCReboot-Sponge/releases
