### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by PixelmonPRO** [ModdedMinecraft/MMCReboot-Sponge#11]
Hello! Could you add localization to this plugin?
I could provide Ru translation) It's just not very convenient to translate through InClassTranslator...
Thanks!)

**Comment by leelawd** [comment]
I was thinking of doing this to all of my plugins eventually.
since I am working on the 2.0 update, I cant think of a better time to add it.

**Comment by leelawd** [comment]
I have a question before I start working on this.

Would you rather have full control over what is stated in the messages through an editable Messages.conf file or have it automatically translate, as I see that sponge has a translation API using locales

**Comment by PixelmonPRO** [comment]
Full control is definitely better, because some phrases have their own specific meaning (or different meanings).
The names of the teams themselves do not need localization, they are all used for original use, only the description is reading :) In the rest it is desirable to have the possibility of manual localization :)
