### ISSUE TITLE
Scheduled Restarts not working

### ISSUE THREAD

**Issue by yepidoodles** [ModdedMinecraft/MMCReboot-Sponge#15]
I set the config to the option below, so in theory the plugin should restart the server at 6am and 6pm server time.

```
autorestart {
    # Values: Fixed, Realtime or None. The value choses here represents what timer will be used.
    enabled=Realtime
    fixed {
        # How long in hours should the auto restart timer be set for?
        interval=6
    }
    realtime {
        # How long in hours should the auto restart timer be set for?
        intervals=[
            "06:00",
            "18:00"
        ]
    }
}
```

However, the server started a countdown for 12pm server time, it didn't shut down the server and is now the timer is running in negatives. 

https://gyazo.com/e35117ad1d003309de550733037c25a1

There were also no errors in console.

**Comment by leelawd** [comment]
Is it possible to get an entire server-log for this time period? I need to see whether or not the scheduler actually initialised.

**Comment by yepidoodles** [comment]
My server logs are impossibly long so I just copied all messages by MMCReboot

https://pastebin.com/RkVJkf1Q

**Comment by leelawd** [comment]
The scheduler seems to be working, at least according to your logs here. Do you know if there was anything like a vote to restart (if you have enabled that) or if someone cancelled anything? (There is supposed to be a check for the real time timer every 15 minutes to reschedule it if it is cancelled.

**Comment by yepidoodles** [comment]
No one has permission to use the commands but me, also even if tps or a player triggered a restart, it should have shut down.

EDIT: also it was exactly on 12pm server time, which would be a bit of coincidence if it wasn't related to the scheduler

**Comment by leelawd** [comment]
Ill do a few internal tests soon. I have some thoughts on what it may be.

If the next timer doesn't cycle through, you could upload the log file to somewhere like google docs or something similar.

**Comment by yepidoodles** [comment]
I've found that it's just the timer;

The server restarts at 6am/6pm as required but the timer starts at 12am/12pm as well (which was in the default config). It knows it doesn't need to restart at 12am/12pm but does the countdown anyway.

**Comment by leelawd** [comment]
Ah ok, I think i have found the issue now. If you set your fixed interval to anywhere between 13-24 , this should be enough to fix it until i can get a proper fix put together.

The handler for the side scoreboard timer is taking both the fixed and realtime intervals.
