### ISSUE TITLE
Won't schedule a reboot

### ISSUE THREAD

**Issue by Jay9519** [ModdedMinecraft/MMCReboot-Sponge#16]
I'm using MMCReboot 2.0.3 on SpongeForge 1.10.2-2281-5.2.0-BETA-2312
whenever I type /reboot start h 12 (or any number) it says the server will restart in whatever time I enter, then I type in /reboot time and it says there is no restart scheduled

Edit: Just seen an update for Sponge, I'll update and try again.... still no good with spongeforge 2313

**Comment by leelawd** [comment]
I believe I know the cause, I will work on a fix first thing tomorrow. Sorry iv been very busy the past few days
