### ISSUE TITLE
Server not restarting automatically on 1.11.2 API6

### ISSUE THREAD

**Issue by Whazaaaaa** [ModdedMinecraft/MMCReboot-Sponge#18]
So either im doing the config wrong or the plugin is faulty atm for API6.

This is my config
`
autorestart {

    # Enable / Disable automatic restarts after the designated interval time.

    enabled=true

    fixed {

        # How long in hours should the auto restart timer be set for?

        interval=3

    }

    # How long in hours should the auto restart timer be set for?

    interval=3

    realtime {

        # Set times for server restarts (24h time eg: 18:30)

        intervals=[

            "00:00",

            "06:00",

            "12:00",

            "18:00"

        ]

    }

}

`
In theory this should restart my server every 3 hours if im correct?
Or is there something im missing because as of right now the server is not restarting every 3 hours.
Using: spongeforge-1.11.2-2315-6.1.0-BETA-2410
and: MMCReboot-2.0.4-API-5.1-6.X

I'd also like to point out this config feels like im doing the same config 3 times.

**Comment by leelawd** [comment]
With the latest version, the config should be like this:

`

    # Values: Fixed, Realtime or None. The value choses here represents what timer will be used.
    enabled=Fixed
    fixed {
        # How long in hours should the auto restart timer be set for?
        interval=3
    }
    realtime {
        # How long in hours should the auto restart timer be set for?
        intervals=[
            "00:00",
            "06:00",
            "12:00",
            "18:00"
        ]
    }
`

In a recent update, it was recommended to reset the config file due to some changes such as the enabled setting switching function

Try this setting and tell me if this works.

**Comment by Whazaaaaa** [comment]
I thought I let it generate a new one perhaps a problem on my side
Ill check it out

**Comment by Whazaaaaa** [comment]
Okay seems that I didnt remove the old config when setting up this server :/
Sorry for the inconvience

**Comment by leelawd** [comment]
No worries, mistakes happen :)
