### ISSUE TITLE
Multi commands in restart?

### ISSUE THREAD

**Issue by PixelmonPRO** [ModdedMinecraft/MMCReboot-Sponge#19]
Hello! I wanted to make a chain of commands when restarting:
```
restart {
    # The command to run if 'use-command' has been enabled
    command=[
        "/pokesave all",
        "/save-all",
        "/stop"
    ]
    # If enabled, This will run the configured command instead of restarting the server.
    use-command=true
```
But, i have next:
`Server выполнил команду: /[pokesave all, save-all, stop]`
Is it possible to do as a multi-commands?

**Comment by leelawd** [comment]
Iv now changed it to this format :)

https://ore.spongepowered.org/leelawd93/MMCReboot/versions/2.1.0
