### ISSUE TITLE
TPS Checker

### ISSUE THREAD

**Issue by Eufranio** [ModdedMinecraft/MMCReboot-Sponge#2]
Would be nice if you have a TPS checker. Each 5 minutes, you check the TPS of the server, and if it's lower than 15 (or an configurable amount in config), the restart will start the countdown. At the end of the countdown, it would check if the TPS is 20 again, if it is, then you cancel the restart. If it still lower than 15, restart the server.

**Comment by leelawd** [comment]
This has been a feature in the back of my mind for a while, I will see what I can do. 

TPS is a tricky thing to deal with, a small spike might set off a false positive. But there's a few things i just thought of that might help with that.

**Comment by Eufranio** [comment]
Yeah, that's why I suggested a new check before stop the server.

**Comment by leelawd** [comment]
This is now in the latest version 1.5. https://github.com/ModdedMinecraft/MMCReboot-Sponge/releases
