### ISSUE TITLE
Tick reboot cancel issue

### ISSUE THREAD

**Issue by Magi1053** [ModdedMinecraft/MMCReboot-Sponge#20]
I have the option to cancel the restart if the TPS is above the minimum. I've had instances during scheduled and manually triggered restarts where the server fails to shutdown at the end of the timer with the message that the TPS is now above the minimum.

**Comment by leelawd** [comment]
Fixed in
https://ore.spongepowered.org/leelawd93/MMCReboot/versions/2.1.1
