### ISSUE TITLE
Server not restarting after stoping

### ISSUE THREAD

**Issue by Noku269** [ModdedMinecraft/MMCReboot-Sponge#21]
the server I am using is stopping fine and broadcasting fine but it is not starting back up at all.
if it helps I'm using https://www.minecraft-hosting.pro/ as the host

**Comment by leelawd** [comment]
Unfortunately this has to do with the control panel they are using, Usually most panels will detect when the server stops and automatically restart it (Which is what this plugin really needs to work) If there is any kind of automatic detection somewhere or ask their support if it is possible to detect when the server stops and to automatically restart it?
