### ISSUE TITLE
restart options

### ISSUE THREAD

**Issue by vaniron** [ModdedMinecraft/MMCReboot-Sponge#23]
Hello, would it be possible to add these 2 features to your mod?

1. players online check = if any player is online, skip the restart
2. before restart commands = send command over console before restarting the server

**Comment by leelawd** [comment]
Sure i can work on adding these. 

For 2, Is that just sending commands right before it stops the server or did you have something else in mind?

**Comment by vaniron** [comment]
One thing, Is it able to restart server based on real system (linux) time instead of uptime?

**Comment by leelawd** [comment]
It is able to do that, just set up the config similar to this: 
[![Screenshot from Gyazo](https://gyazo.com/390041066931cc43d42922e9abfac8ad/raw)](https://gyazo.com/390041066931cc43d42922e9abfac8ad)
