### ISSUE TITLE
Could not pass FMLInitializationEvent to Plugin

### ISSUE THREAD

**Issue by andrebpessoa** [ModdedMinecraft/MMCReboot-Sponge#28]
When I start the server, this appers on the log and I can't use the plugin: https://pastebin.com/vkdnwSd6

And further, this appears: https://pastebin.com/SgZdhZzm

**Comment by leelawd** [comment]
This appears to be an error from something in your config file. It doesn't like the way it is layed out (presumably after editing it)

**Comment by andrebpessoa** [comment]
uhhhh, my bad... I messed up with the configs :/

**Comment by leelawd** [comment]
no problem, easy mistake :)
