### ISSUE TITLE
Only shutting down server?

### ISSUE THREAD

**Issue by Gebcrafter** [ModdedMinecraft/MMCReboot-Sponge#29]
It has a countdown that works normally, and then it shuts down the server, but, that's it. It doesn't come back up.

The server is not running on a dedicated machine.

Here's a log:
https://pastebin.com/RtEZhfGQ

**Comment by 0Fox** [comment]
Plugin should not, and really can't boot it back because he part of the server.
Look on your hosting for something like auto-reboot in case of server crash, enable it and you will get what you want.

**Comment by 0Fox** [comment]
And after looking logs, looks like it is dedicated server, just on your desktop pc... In this case you can use this .bat file
```
:Start
java -Xms2G -Xmx2G  -jar forge-1.12.2-14.23.4.2705-universal.jar
pause

GOTO Start
```

**Comment by Gebcrafter** [comment]
Hmm, alright. I will use this batch file (with the correct RAM allocations and jar name, of course). I'm relatively new at anything-other-than-basic level server administration. I'll see how it works, thank you for the help!

**Comment by leelawd** [comment]
similar to #26
