### ISSUE TITLE
Add zh language file. 添加ZH语言文件。

### ISSUE THREAD

**Issue by CJYKK** [ModdedMinecraft/MMCReboot-Sponge#34]
This is zh_CN language file.
[messages_ZH.conf.txt](https://github.com/ModdedMinecraft/MMCReboot/files/5750781/messages_ZH.conf.txt)
(Change file type)
Please add it, thank you!

**Comment by CJYKK** [comment]
I almost forgot that I created this issue. I didn’t even know how to use PR at that time lol

**Comment by leelawd** [comment]
Its been a little while, i did put it in a while ago but just forgot about the github entirely until i got back into my projects recently
