### ISSUE TITLE
% of players to say yes not working

### ISSUE THREAD

**Issue by Whazaaaaa** [ModdedMinecraft/MMCReboot-Sponge#6]
So either im doing something wrong of this has never worked but in the config theres an option to set the % of players on the server that has to say yes in order for a restart to succeed. 

Now I've had it plenty of times with 20 players that just 5 people was okay while I have it set to 80%
So I have this set:

`# % of online players to vote yes before a restart is triggered.'
   ' vote-percent=80`

Which I would think that 80% of players aka 16/20 would have to vote yes. Maybe this percentage is for something completely different but that is how I see.

Am I wrong or has this been an issue from the start?

Thanks for the plugin the restarts are very nice!

**Comment by leelawd** [comment]
I have no idea how this has slipped past unnoticed until now. But it seems i have forgotten to include this setting within the voting algorythm. I will work on adding it soon.

**Comment by Whazaaaaa** [comment]
Been using this for months with this problem but seeing as you're updating and I still had the problem I thought it was time to hopefully get it fixed. Good to know I wasnt gooing mad :)

**Comment by leelawd** [comment]
I haven't been able to test this due to not having enough people. Hopefully this addition fixes this issue
https://github.com/ModdedMinecraft/MMCReboot-Sponge/releases/tag/1.7.1

**Comment by leelawd** [comment]
Gonna close this as I'm sure this has been fixed.
