### ISSUE TITLE
Request: Custom Sound.

### ISSUE THREAD

**Issue by Magi1053** [ModdedMinecraft/MMCReboot-Sponge#7]
Currently you can toggle to play a sound during shutdown at each broadcast interval.
I would like to be able to enter in a custom sound, as well as the option to only have it play once. This is for music that would sound dumb if repeated. Obviously you would then have to stop that sound if the reboot is canceled.

**Comment by leelawd** [comment]
Sure, i will add this when i get time to do so.

**Comment by Magi1053** [comment]
Additionally, a config for the sound volume,

**Comment by leelawd** [comment]
Sure thing, is the default volume too loud or too quiet?

**Comment by Magi1053** [comment]
It's fine for a ping, however minecraft has a sound volume cap, so if you exceed that cap, it doesn't actually make the sound louder, but can be audible from longer distances. Doing this will allow the music to be heard to the player even if they move away from the music origin.

**Comment by leelawd** [comment]
Ah, yea. The movement thing was something i was just playing around with since i knew it would be an issue if you wanted to have music playing instead of a single beep.

The previous method was using just the players location, so I knew I would have to change it over to just broadcast from 1 location at the centre of the world, instead of per player as it would overlap each other.

**Comment by Magi1053** [comment]
Would it overlap though?
```
for(Player p : Sponge.getServer().getOnlinePlayers()) {
    if (Config.playSoundEnabled) {
        p.playSound(SoundTypes.BLOCK_NOTE_PLING, p.getLocation().getPosition(), 2);
    }
}
```
You're only playing the sound to that player. The sound is only clientside, so broadcasting the music at the player's location, and increasing the volume would be functionally identical as starting the music for everyone at a single position.

Reguardless, playing the music at 0 ~ 0 with volume 'whatever' would work too, personal preference I guess

**Comment by leelawd** [comment]
Now that i actually think about it, maybe not. But I think that just broadcasting it from a single source would be better.  Since it would still be heard even if the player teleports away or to another dimension

**Comment by Magi1053** [comment]
Side note, when would the sound start playing with an autorestart ?

**Comment by leelawd** [comment]
It is currently in sync with the warning messages

**Comment by Magi1053** [comment]
That would mean that the music would start playing at the earliest broadcast message, which could be hours away from the actual restart.

**Comment by leelawd** [comment]
Yea, I would need to setup an extra setting for the first sound broadcast.

**Comment by Magi1053** [comment]
An alternative to this whole idea is to execute a command set in the config at a set interval / minimum time, such as
`/execute @a ~ ~ ~ playsound block.note.pling block @p ~ ~ ~ {volume}`
which would run playsound for every player

**Comment by leelawd** [comment]
I would still need to set it up in a similar fashion to the warning timers, we will see how things go though.

**Comment by leelawd** [comment]
There is a few issues iv ran into in regards to playing music in this way,

1. If the player teleports to another dimension, the sound will stop playing until another warning with sound is sent.
2. Sponge doesnt have anything like a /stopsound function
3. If the warning is played every minute with a sound that lasts longer than 1 minute, the new sound will play along with the previous sound.

**Comment by leelawd** [comment]
Well, just an update stating that this has been implemented for v2.0 but the above stated issues will still be a problem and will be fixed when and if a way is put in to fix them.

**Comment by Magi1053** [comment]
No worries, I've forked this at b1d8a059fab4cf9992a5e2c4cd93b9d6504d2dc0 and implemented this feature myself, highly customized to meet the requirements of my server.

**Comment by Magi1053** [comment]
Just wondering if this was fully implemented
