### ISSUE TITLE
Time: Seconds instead of minutes

### ISSUE THREAD

**Issue by TomberWolf** [ModdedMinecraft/MMCReboot-Sponge#8]
The topic say it: Could you please change the timer format to seconds instead of minutes?
Would be much more precise.

**Comment by leelawd** [comment]
I assume you are talking about the broadcast timer here?

**Comment by TomberWolf** [comment]
Oh, yes! Sorry.

**Comment by leelawd** [comment]
Added in 40414d975ff940851714e6f2f1c061dbf02ab7b8

Will be in the next release soon.
