### ISSUE TITLE
Auto restart not working.

### ISSUE THREAD

**Issue by Magi1053** [ModdedMinecraft/MMCReboot-Sponge#9]
I set my auto restart to 6 hours in the config as shown below, however it's been 14 hour and the server still hasn't shutdown.
```
autorestart {
    # Enable / Disable automatic restarts after the designated interval time.
    enabled=true
    # How long in hours should the auto restart timer be set for?
    interval=6
}
```

**Comment by leelawd** [comment]
Could you provide the FML server log file for the time that this happened?

**Comment by Magi1053** [comment]
Issue is not replicable
